server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  profiles:
    thymeleaf.prefix: classpath:/templates
    aop.auto: true
   #freemaker
    freemarker.suffix: .ftl
    freemarker.templateEncoding: UTF-8
    freemarker.templateLoaderPath: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.xiaoshangxing.com:5847/sbpractice?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: sbpractice
    password: abc1073794822!
  logging:
    config: classpath:logback.xml

 # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
          open: false  # 是否开启redis缓存  true开启   false关闭
          database: 0
          host: redis.open.renren.io
          port: 16379
          password:       # 密码（默认为空）
          timeout: 6000  # 连接超时时长（毫秒）
          #pool:
              #max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
              #max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
              #max-idle: 10      # 连接池中的最大空闲连接
              #min-idle: 5
          jedis:  #2.0需要声名采用的是jedis客户端链接，默认是lettuce客户端
            pool:
              max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
              max-wait:
              max-idle: 10     # 连接池中的最大空闲连接
              min-idle: 5      # 连接池中的最小空闲连接
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect

